{% set version = "4.4.4" %}

package:
  name: netcdf-fortran
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-fortran/archive/v{{ version }}.tar.gz
  sha256: 44b1986c427989604df9925dcdbf6c1a977e4ecbde6dd459114bca20bf5e9e67


build:
  number: 7
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - libnetcdf 4.5.0
    - hdf5 1.10.1
    - pkg-config  # [not win]

  host:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - libnetcdf 4.5.0
    - hdf5 1.10.1
    - pkg-config  # [not win]

  run:
    - libnetcdf 4.5.0
    - hdf5 1.10.1
    - libgcc-ng
    - libgfortran-ng  

test:
  commands:
    - nf-config --all  # FIXME: no nf-config for cmake
    - test -f ${PREFIX}/lib/libnetcdf.a  # [unix]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/Unidata/netcdf-fortran
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  summary: 'Unidata NetCDF Fortran Library.'

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
